modLoader="javafml"
loaderVersion="[31,)"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://github.com/mcdli5/NihilFit/issues"

[[mods]]
modId="nihilfit"
version="${version}"
displayName="Nihil Fit"
# updateJSONURL=""
displayURL="http://github.com/mcdli5/NihilFit"
logoFile="nihilfit.png"
# credits=""
authors="mcdli5"
description='''
Ex Nihilo Nihil Fit
'''

[[dependencies.nihilfit]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.nihilfit]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"