modLoader="javafml"
loaderVersion="[31,)"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="http://github.com/mcdli5/ExNihilo/issues"

[[mods]]
modId="exnihilo"
version="${version}"
displayName="Ex Nihilo"
# updateJSONURL=""
displayURL="http://github.com/mcdli5/ExNihilo"
logoFile="exnihilo.png"
# credits=""
authors="mcdli5"
description='''
Ex Nihilo
'''

[[dependencies.exnihilo]]
modId="forge"
mandatory=true
versionRange="[31,)"
ordering="NONE"
side="BOTH"

[[dependencies.exnihilo]]
modId="minecraft"
mandatory=true
versionRange="[1.15.2]"
ordering="NONE"
side="BOTH"